### ISSUE TITLE
20/03/2020 | Team-the-104-Fornax

### ISSUE THREAD

**Issue by rajkumardas2701** [OdongAlican/newsweek.com-home-page#1]
- Get Bootstrap CSS on your local machine
- Add responsiveness to the Nav Bar
- Align columns as it appears on the original page.

**Comment by OdongAlican** [comment]
## Bootstrap CSS
This was achieved using a CDN

## Responsiveness and Alignment
The files are now aligned as required on the page and responsiveness was achieved using Bootstrap Grid
