### ISSUE TITLE
24/03/2020 - Team 104 The Fornax

### ISSUE THREAD

**Issue by tacodtripe** [OdongAlican/newsweek.com-home-page#2]
Good work, right now it looks the same as the original page.
Just one recommendation in order to fulfill the main reason for the project:
- Try to embed the .css attributes using the homologs bootstrap classes, this might help you to master the bootstrap use by the time you finish the webpage.

Keep up the great work man, cheers.

**Comment by OdongAlican** [comment]
That has been achieved. There is limited use of custom CSS in the project. Thanks a lot for the recommendation
